set :application, 'pyowa'
set :scm, :git
set :repo_url, 'https://github.com/mattjmorrison/pyowa-deploy.git'
set :django_project_dir, ''
set :django_settings_dir, 'pyowa/settings'
set :wsgi_path, 'pyowa'
set :pip_requirements, 'requirements.txt'
set :compilemessages, true
set :service, 'nginx'
